spring:
  datasource:
    username: "subin"
    password: "pass"
    url: "jdbc:postgresql://localhost:5432/springboot"

  jpa:
    hibernate:
      ddl-auto: "validate"
    generate-ddl: false
    show-sql: true